### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kg4zow** [yishilin14/asc-key-to-qr-code-gif#4]
In your `README.md` file, can you add an explanation of why somebody might *want* to convert their PGP public key into a QR code, i.e. what would somebody do with such a QR code? I ask because I've been using PGP since the early 1990's, and I've never heard of anybody converting their key to a QR code before.

Also, please explain what an *animated* QR code is and why you would need one in this case.

**Comment by yishilin14** [comment]
This script is a by-product of https://github.com/mssun/passforios.

Say Bob wants to "copy" his key from his computer to his phone. He could first convert his key to a QR code. Then, he could use his phone to scan and decode it. Mission accomplished!

Unfortunately, a private key file could be too large to fit into a single QR code that can be scanned and decoded by a phone correctly. In this case, Bob could use the script to cut his key into small pieces and convert them piece by piece, and get a sequence of QR codes.

I I will update the readme file later. :-)

**Comment by yishilin14** [comment]
Just updated the readme.

**Comment by TrevCan** [comment]
Hey, I think you should probably add to the docs/README the fact that **_two qr code images_** are supposed to be displayed **per key**, as this is not in the documentation. I was using a static image viewer so the gif would only show one of the two qr codes... I'll also add this to the main *passforios/* repo.
